backbone:
  name: resnet50

model:
  num_classes: 10
  input_channels: 3

optimizer:
  name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  name: step
  step_size: 10
  gamma: 0.1

dataset:
  name: cifar10
  batch_size: 128
  data_dir: ./datasets/cifar10
  num_classes: 10
  augmentation:
    train:
      - type: RandomCrop
        size: 32
        padding: 4
      - type: RandomHorizontalFlip
      - type: ToTensor
      - type: Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010] 
    
    test:
      - type: ToTensor
      - type: Normalize
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010] 